### ISSUE TITLE
Parameters don't display correctly when Distance Functions have parameters.

### ISSUE THREAD

**Issue by Michaeljfang** [Michaeljfang/PyGAAP#4]
To reproduce:
1. Go to the analysis methods tab,
2. select an analysis method and a distance function that has its own parameters.

Below is with "Cosine Distance (vectorized)".
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "***/PyGAAP/backend/GUI/GUI_unified_tabs.py", line 258, in <lambda>
    list_of_functions["find_parameters"](frame, lb, dp, module_type = parameters_content), add = "+")
  File "***/PyGAAP/backend/GUI/GUI2.py", line 1430, in find_parameters
    displayed_param_name = this_module._variable_options[parameter_i].get("displayed_name", parameter_i)
KeyError: 'normalized'
```

**Comment by Michaeljfang** [comment]
Attempted to address in 20230414 ([c4ec31d](https://github.com/Michaeljfang/PyGAAP/commit/c4ec31d70c519bca81926809924c02847778dfd9))
